package pack;


import java.io.IOException;

public class Demo
{
	void disp3()throws IOException
	{
		int num=20;
		if(num>10)
		{
			throw new IOException();
		}
	}
	void disp2()throws IOException
	{
		disp3();
	}
	void disp1()throws IOException
	{
		disp2();
	}
	public static void main(String args[])
	{
		Demo j=new Demo();
		try {
			j.disp1();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} // compilation error : add throws or try_catch
	}
}						
